### ISSUE TITLE
What is the difference between this and alexzorin/authy?

### ISSUE THREAD

**Issue by impredicative** [token2/authy-migration#2]
This repo is a fork of [alexzorin/authy](https://github.com/alexzorin/authy). What is the changelog since it was forked?

**Comment by token2** [comment]
As reflected in the readme, the primary focus has shifted to repurposing the code to facilitate profile migration onto our hardware tokens. This includes enhancements in export file formats, integration of QR codes compatible with NFC burners, and more.

**Comment by impredicative** [comment]
Can the "About" section of the repo perhaps be edited to mention it?

It currently has its default value:

> No description, website, or topics provided.

**Comment by token2** [comment]
> Can the "About" section of the repo perhaps be edited to mention it?
> 
> It currently has its default value:
> 
> > No description, website, or topics provided.

Users in most cases navigate from our website to this github repo, not vice versa. But we have added the link and a brief description.
