### ISSUE TITLE
Cant get this to work; decryption failed; cant import into Aegis

### ISSUE THREAD

**Issue by dimyself** [token2/authy-migration#3]
Hi there. I'm on linux and Dont see the portable app for linux linked in the instructions? I only see a portable windows version?

I installed Go and went through the help here in your github

I add the new device successfully, and it does locate my authy accounts, but I just get this error "2023/12/14 14:46:21 Failed to decrypt token <account_name> (authenticator): decryption failed

And I get this for all accounts in authy. 

I am using the correct backup password that is located in authy settings!

I've also tried disabling authy backup password, and it still fails to decrypt

Even though I get this error.... I do still have the exported html and txt files it generates (i've tried both html and txt).

None of these files will import into Aegis app. I just get error: "Value 0 of type java.lang.integer cannot be converted to JSONObject"

I've also tried importing the authy-go.json file into Aegis. 

I've tried importing all these generated files into Aegis and none of it is working

why isnt the decryption working using the Go tool when I enter the correct "backup key" password (or if i disable it all together)? Or am i trying the wrong password?

I see no mention of how to handle this error or what i'm doing wrong??

Thank you!

**Comment by token2** [comment]
Hello,
It appears to be due to a wrong password indeed. We will ask our team to retest and update.

P.S. As you are not using this tool to import to Token2 hardware tokens, it would be logical to raise this issue also with the original project https://github.com/alexzorin/authy - our project relies on this (the additional code is for provisioning with hardware tokens, which is not your case).

**Comment by token2** [comment]
> why isnt the decryption working using the Go tool when I enter the correct "backup key" password (or if i disable it all together)? Or am i trying the wrong password?
> 
 
We replicated your issue and retested the flow. It works fine if Backup password is correct, and throws "decryption failed" **if you provide a wrong password.**

**Comment by token2** [comment]
Issue not related to the code itself
