### ISSUE TITLE
Outdated Access Key

### ISSUE THREAD

**Issue by akazakou** [token2/authy-migration#7]
Thanks for that beautiful tool, unfortunately, an access key is not valid anymore. 

Can we update it or use some workaround here?

**Comment by token2** [comment]
Hi @akazakou - there is no "access key" as such used, it fully emulates the native app. 
If you gen an error similar to 

>  Failed to decrypt token <TOTP Profile>: decryption failed

 Then the issue is simply a wrong password being entered.
 
 P.S. Just tested with the latest version of the script, works fine.

**Comment by akazakou** [comment]
Unfortunately there is `permission denied` error

**Comment by token2** [comment]
@akazakou we still cannot reproduce the issue. Can you please clarify at which step exactly you get this error? A screenshot would be great.

**Comment by akazakou** [comment]
Sorry. Looks like my bad. I've tried to reproduce a bug and right now everything working fine on my Mac. Sorry for the interruption and thank you a lot for your help and that great tool!
