### ISSUE TITLE
No html file generated

### ISSUE THREAD

**Issue by TerminatedGA** [token2/authy-migration#8]
I am able to use the compiled version until the 'TOTP profile migration file is being generated' message with no decryption error, but no HTML file is generated in the folder.

**Comment by token2** [comment]
@TerminatedGA we retested the portable app and could not replicate the issue. Can you check the folder permissions? You can also try to run the exe from a Temp folder

**Comment by victorelec14** [comment]
i have the same problem with the portable version

```
Export file name -.txt for Molto2 and .html for regular TOTP profiles  : export.html
File: export.html2024/02/27 20:13:01 Found existing device registration
2024/02/27 20:13:02 Authy User ID 479xxx, Device ID 932xxxx
2024/02/27 20:13:02 Please provide your Authy TOTP backup password:
2024/02/27 20:13:10 TOTP profile migration file is being generated:

2024/02/27 20:13:10 Failed to decrypt token xxxxxxxx: decryption failed
2024/02/27 20:13:10 Failed to decrypt token xxxx:xxxxxxxxxxxx: decryption failed
```

thx

**Comment by token2** [comment]
> i have the same problem with the portable version
> 2024/02/27 20:13:10 Failed to decrypt token xxxxxxxx: decryption failed
> 2024/02/27 20:13:10 Failed to decrypt token xxxx:xxxxxxxxxxxx: decryption failed

This is a different issue. "decryption failed" is caused by a wrong backup password provided.

**Comment by victorelec14** [comment]
> I am able to use the compiled version until the 'TOTP profile migration file is being generated' message with no decryption error, but no HTML file is generated in the folder.

@TerminatedGA That happens to me when I put the name without the ".html" extension, was that your case?

you can use for example "export.html" 

> Export file name -.txt for Molto2 and .html for regular TOTP profiles  : export.html

**Comment by alex4108** [comment]
@victorelec14 exactly the case for me, used a full path like `D:\Path\to\dir\totp` and got nothing.  Using `D:\Path\to\dir\totp.html` worked for me.

**Comment by token2** [comment]
>like D:\Path\to\dir\totp and got nothing

This behavior is expected. The format of the output file is determined by the file extension. For instance, '.html' yields a list of QR codes, '.txt' generates tab-separated Molto2 format, '.wa.txt' provides a list of URIs for WinAuth, etc. If you don't specify any extension, no output will be produced.

**Comment by TerminatedGA** [comment]
This is correct, I forgot to add .html when writing the file name. Perhaps add an error when no file extension is specified? Or default to .html when no extension is given?
