### ISSUE TITLE
package git is not in GOROOT

### ISSUE THREAD

**Issue by gabsoftware** [token2/authy-migration#9]
I followed the instructions and when I type:
```go run git clone https://github.com/token2/authy-migration.git```
It gives me:
```package git is not in GOROOT (/usr/lib/go-1.15/src/git)```

**Comment by gabsoftware** [comment]
Ok I think there's just a typo in the instructions...
The correct line to type is simply:
```go run authy-export.go```

**Comment by gabsoftware** [comment]
Worked very well. Now I could successfully migrate to 2FAS. Thanks a lot!

**Comment by token2** [comment]
Thanks for reporting. Typo fixed
